---
- hosts: localhost
  vars:
    dns_tld: "{{canonical_tld}}"
    dns_subdomains:
      - subdomain: "{{service}}"
        ip: "{{swarm_ip}}"
    kong_api:
      name: "{{service}}"
      upstream_url: "http://{{service}}:80"
      hosts: "{{service}}.{{canonical_tld}}"
    kong_plugins: []
    # kong_plugins:
    # - name: cors
    #   config: {}
    # - name: rate-limiting
    #   config:
    #     config.second: 10
    #     config.hour: 10000
    # status:
    WebsiteName: "{{entity_name}}"
    WebsiteURL: "https://{{service}}.{{canonical_tld}}"
    CheckRate: 300
    TestTags: ''
  roles:
    - role: dns
      tags: [dns]
    - role: kongapi
      tags: [kong]
    - role: status
      tags: [status]

- hosts: server_swarm
  vars:
    # docker app setup:
    # see: roles/djangoapp/defaults/main.yml for more:
    docker_org: "{{organization}}"
    docker_image: "{{service}}"
    docker_service: "{{service}}"
    docker_command: "sh /code/run.sh"
    aws_backups_bucket: "media-appointmentguru"
    aws_region: "eu-central-1"
    postgres_passwords:
      authenticationguru: "C5AB0266-B9A3-4B64-9509-16D5BB962D0D"
  roles:
    - role: djangoapp
      tags: [app, django, deploy]

  post_tasks:
    - name: Tell slack
      slack:
        token: '{{slack_token}}'
        msg: 'Deployed: {{docker_service}} using image: {{docker_org}}/{{docker_image}}:{{docker_version}}. See: {{service}}.{{canonical_tld}}'
      delegate_to: localhost
      when: slack_token is defined
      tags: deploy
      run_once: true